Implementation of two RSTM with elliptic relaxation models
==========================================================
Heng Xiao <xiaoheng2011@gmail.com>

Implementation: Heng Xiao +
Review: Michael Wild +
Bug reports and comments to: Heng Xiao

The following RSTM models are implemented:

`Durbin`::
  Durbin Elliptic Relaxation Model <<Durbin1993>>
`ManceauHanjalic`::
  Hanjalic Elliptic Blending Model <<Manceau2002>>

Both classes inherit from the abstract base class `GenElliptic`. Both can
choose 'LRR' or 'SSG' as the homogenous model. However, 'SSG' has not been
fully tested. 'LRR' is the default. The `Durbin` model also has the option of
applying the elliptic operator correction by Manceau et al <<Manceau2001>>.
This is invoked by setting `ellipticOperatorCorrection` to be 'true'.

This distribution also comes with a solver `channelPisoFoam` for the
computation of channel flow with fixed mass flux. The solver is derived from
`channelFoam`, but can use RAS turbulence models. The turbulece models,
however, can be used with any solver.

An example case, the Re395 channel, is also included.

.Building the code:
  $ ./Allwmake

.Runnning the example:
  $ blockMesh -case channel395-Durbin-example
  $ channelPisoFoam -case channel395-Durbin-example

[bibliography]
References
----------

[bibliography]
- [[[Durbin1993]]] Durbin, 'A Reynolds stress model for near-wall turbulence'.
  J Fluid Mech 249, 1993. http://dx.doi.org/10.1017/S0022112093001259

- [[[Manceau2002]]] Manceau and Hanjalic, 'Elliptic blending model: a new
  near-wall Reynolds-stress turbulence closure'. Phys Fluid 14 (74), 2002.
  http://dx.doi.org/10.1063/1.1432693

- [[[Manceau2001]]] Manceau, Wang, and Laurence, 'Inhomogeneity and anisotropy
  effects on the redistribution term in Reynolds-averaged Navier-Stokes
  modelling'. J Fluid Mech 438, 2001.
  http://dx.doi.org/10.1017/S0022112001004451
